version: "3"
services:
  app:
    build:
      dockerfile: ./development.dockerfile
      context: .
    container_name: ${APP_NAME}_node
    command: yarn dev
    volumes:
      - /api/uploads:/api/uploads
      - ./:/usr/src/app
    depends_on:
      - "mongodb"
    environment:
      - HOST=${HOST}
      - MONGO_URI=${MONGO_URI}
    network_mode: host
    # ports:
    #   - "3000:3000"
    # networks:
    #   - cms
  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME}_mongo
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    network_mode: host

    # ports:
    #   - "27017:27017"
    # networks:
    #   - cms

# networks:
#   cms:
#     driver: bridge
volumes:
  mongodb:
  mongodb_config:
