version: "3"
services:
  app:
    # user: $USER
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: ${APP_NAME}_node
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ${DOCKER_VOLUMES_DATA_PATH}/${APP_NAME}/uploads:/usr/src/app/api/uploads
    networks:
      - cms
    depends_on:
      - "mongodb"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb
  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME}_mongo
    volumes:
      - ${DOCKER_VOLUMES_DATA_PATH}/${APP_NAME}/mongodb_data:/data/db
      - ${DOCKER_VOLUMES_DATA_PATH}/${APP_NAME}/mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - cms

networks:
  cms:
    driver: bridge

