version: "3"
services:
  app:
    # user: $USER
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: ${APP_NAME}_node
    command: yarn start
    volumes:
      - ${DOCKER_VOLUMES_DATA_PATH}/${APP_NAME}/uploads:/usr/src/app/api/uploads
    depends_on:
      - "mongodb"
    environment:
      - HOST=${HOST}
      - MONGO_URI=${MONGO_URI}
    restart: always
    network_mode: host
    # ports:
    #   - "3000:3000"
    # networks:
    #   - cms
  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME}_mongo
    volumes:
      - ${DOCKER_VOLUMES_DATA_PATH}/${APP_NAME}/mongodb_data:/data/db
      - ${DOCKER_VOLUMES_DATA_PATH}/${APP_NAME}/mongodb_config:/data/configdb
    restart: always 
    network_mode: host

    # ports:
    #   - "27017:27017"
    # networks:
    #   - cms

# networks:
#   cms:
#     driver: host

